from .replica_cliente_credito import *
from .replica_cliente import *
from .replica_cobranza import *
from .replica_cobros import *
from .replica_compras import *
from .replica_cxc import *
from .replica_devolucion_compra import * 
from .replica_embarques import * 
from .replica_existencia import *
from .replica_fichas import  *
from .replica_inventarios import *
from .replica_morrallas import *
from .replica_movimientos_inventario import *
from .replica_producto import *
from .replica_proveedor import * 
from .replica_recepcion_compra import *
from .replica_requisicion_material import *
from .replica_traslados import *
from .replica_vales import *
from .replica_cancelacion_cfdi import *
from .replica_movimiento_almacen import *